export const REMINDER = [
    {
        "reminder_id": 3,
        "morning_time": "09:25:00",
        "noon_time": "13:30:00",
        "evening_time": null,
        "night_time": null,
        "medicine_id": 4,
        "patient_id": 2,
        "number_of_medication": 10,
        "medicine_name": "ยาลดการเกาะตัวของเม็ดเลือด",
        "treatment": "ช่วยลดความเสี่ยงในการเกิดการเกาะตัวของเม็ดเลือด",
        "number_of_times_per_day": 1,
        "amount_per_time": 1,
        "period": "ก่อนอาหาร2",
        "medicine_image": "https://media.discordapp.net/attachments/1090253725647523921/1093960018778402917/anticoagulant-and-antiplatelet-drugs_thumb-1-732x549.png?width=582&height=436",
        "id_card": "1711000121111",
        "firstName": "อาภัสรา",
        "lastName": "โมรัษเฐียร",
        "date_of_birth": null,
        "weight": null,
        "height": null,
        "congenital_disease": null,
        "history_of_drug_allergy": null,
        "patient_image": null
    },
    {
        "reminder_id": 4,
        "morning_time": "08:25:00",
        "noon_time": "12:30:00",
        "evening_time": null,
        "night_time": null,
        "medicine_id": 1,
        "patient_id": 2,
        "number_of_medication": 10,
        "medicine_name": "ยาลดการเต้นของหัวใจ",
        "treatment": "ช่วยลดความเสี่ยงในการเกิดการเกาะตัวของเม็ดเลือด",
        "number_of_times_per_day": 1,
        "amount_per_time": 1,
        "period": "ก่อนอาหาร",
        "medicine_image": "https://media.discordapp.net/attachments/1090253725647523921/1093951369515368448/5850.png?width=581&height=436",
        "id_card": "1711000121111",
        "firstName": "อาภัสรา",
        "lastName": "โมรัษเฐียร",
        "date_of_birth": null,
        "weight": null,
        "height": null,
        "congenital_disease": null,
        "history_of_drug_allergy": null,
        "patient_image": null
    }
]